In [1]:
# ==============================================================
# 📌 ENCODING  TECHNIQUES IN MACHINE LEARNING
# ==============================================================

"""
WHY DO WE NEED ENCODING?

Machine Learning algorithms work with numbers.
Categorical variables (text data) must be converted into numeric format.

Encoding is the process of converting categorical features into numerical values
without introducing incorrect relationships.
"""

# --------------------------------------------------------------
# 1️⃣ Sample Dataset
# --------------------------------------------------------------

import pandas as pd

data = {
    "Color": ["Red", "Blue", "Green", "Blue", "Red"],
    "Education": ["High School", "Graduate", "Postgraduate", "Graduate", "High School"],
    "City": ["Delhi", "Mumbai", "Delhi", "Chennai", "Mumbai"],
    "Purchased": [1, 0, 1, 0, 1]   # Target variable
}

df = pd.DataFrame(data)
df

   Color     Education     City  Purchased
0    Red   High School    Delhi          1
1   Blue      Graduate   Mumbai          0
2  Green  Postgraduate    Delhi          1
3   Blue      Graduate  Chennai          0
4    Red   High School   Mumbai          1

In [2]:
# --------------------------------------------------------------
# 2️⃣ LABEL ENCODING
# --------------------------------------------------------------

"""
Label Encoding assigns a unique number to each category.

⚠️ Problem:
It introduces an artificial order between categories.

Example:
Red=2, Blue=0, Green=1
Model may assume Red > Green > Blue (which is wrong).

Best used for:
- Ordinal data
- Tree-based models
"""

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df_label = df.copy()
df_label["Color"] = le.fit_transform(df_label["Color"])

df_label

   Color     Education     City  Purchased
0      2   High School    Delhi          1
1      0      Graduate   Mumbai          0
2      1  Postgraduate    Delhi          1
3      0      Graduate  Chennai          0
4      2   High School   Mumbai          1

In [3]:
# --------------------------------------------------------------
# 3️⃣ ORDINAL ENCODING
# --------------------------------------------------------------

"""
Used when categories have a natural order.

Example:
High School < Graduate < Postgraduate

Here, order is meaningful.
"""

from sklearn.preprocessing import OrdinalEncoder

df_ordinal = df.copy()

ordinal_encoder = OrdinalEncoder(
    categories=[["High School", "Graduate", "Postgraduate"]]
)

df_ordinal["Education"] = ordinal_encoder.fit_transform(
    df_ordinal[["Education"]]
)

df_ordinal

   Color  Education     City  Purchased
0    Red        0.0    Delhi          1
1   Blue        1.0   Mumbai          0
2  Green        2.0    Delhi          1
3   Blue        1.0  Chennai          0
4    Red        0.0   Mumbai          1

In [6]:
# --------------------------------------------------------------
# 5️⃣ ONE-HOT ENCODING USING SKLEARN
# --------------------------------------------------------------

from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder(sparse=False)

encoded = ohe.fit_transform(df[["City"]])

encoded_df = pd.DataFrame(
    encoded,
    columns=ohe.get_feature_names_out(["City"])
)

encoded_df

TypeError: OneHotEncoder.__init__() got an unexpected keyword argument 'sparse'

In [7]:
# --------------------------------------------------------------
# 5️⃣ ONE-HOT ENCODING USING SKLEARN
# --------------------------------------------------------------

from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder(sparse=False)

encoded = ohe.fit_transform(df[["City"]])

encoded_df = pd.DataFrame(
    encoded,
    columns=ohe.get_feature_names_out(["City"])
)

encoded_df

TypeError: OneHotEncoder.__init__() got an unexpected keyword argument 'sparse'

In [8]:
# --------------------------------------------------------------
# 6️⃣ FREQUENCY ENCODING
# --------------------------------------------------------------

"""
Replace category with its frequency count.

Useful when:
- Many unique categories
- Tree-based models
"""

df_freq = df.copy()

freq_map = df_freq["City"].value_counts().to_dict()
df_freq["City"] = df_freq["City"].map(freq_map)

df_freq

   Color     Education  City  Purchased
0    Red   High School     2          1
1   Blue      Graduate     2          0
2  Green  Postgraduate     2          1
3   Blue      Graduate     1          0
4    Red   High School     2          1

In [9]:
# --------------------------------------------------------------
# 7️⃣ TARGET ENCODING (Manual Implementation)
# --------------------------------------------------------------

"""
Replace category with mean of target variable.

Powerful but risk of data leakage if done before train-test split.
"""

df_target = df.copy()

target_mean = df_target.groupby("City")["Purchased"].mean()

df_target["City"] = df_target["City"].map(target_mean)

df_target

   Color     Education  City  Purchased
0    Red   High School   1.0          1
1   Blue      Graduate   0.5          0
2  Green  Postgraduate   1.0          1
3   Blue      Graduate   0.0          0
4    Red   High School   0.5          1